services:
  checker:
    build: .
    platform: linux/amd64
    restart: unless-stopped
    attach: false
    tty: false
    volumes:
      - wallet:/usr/key
      - log:/aethir-node/log
  cli:
    build: .
    platform: linux/amd64
    command: ./AethirCheckerCLI
    attach: false
    tty: true
    stdin_open: true
    volumes:
      - wallet:/usr/key
    network_mode: "service:checker"
    depends_on:
      - checker

  telegraf:
    profiles:
      - with-metrics
    image: telegraf:alpine
    ports:
      - target: 9273
        published: 9273
    volumes:
      - log:/aethir-node-log
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

volumes:
  wallet:
  log:
