apiVersion: 1
prune: true
datasources:
  - name: prometheus
    uid: edv1gyg3xxwjke
    orgId: 1
    type: prometheus
    url: http://prometheus:9090
    editable: true
    version: 1
    access: proxy

