{
 "title": "Aethir Checker Node Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Checker Node process/container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Checker log",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 1 },
   "targets": [
    { "expr": "tail_logentry{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Log entries by severity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "count by(level) (tail_logentry)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Checker Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "procstat_cpu_usage", "legendFormat": "{{cmdline}}" },
    {
     "expr": "avg(rate(procstat_cpu_time_iowait[$__rate_interval]))",
     "legendFormat": "IO Wait"
    }
   ]
  },
  {
   "title": "Bytes sent/recvd (Container interfaces)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(interface) (rate(net_bytes_recv[$__rate_interval]))",
     "legendFormat": "RX/{{interface}}"
    },
    {
     "expr": "avg by(interface) (rate(net_bytes_sent[$__rate_interval]))",
     "legendFormat": "TX/{{interface}}"
    }
   ]
  },
  { "title": "Host stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Host CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by(cpu)(irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))*100)",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Disk space available on Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "{{mountpoint}}" }
   ]
  },
  {
   "title": "Available memory on Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}